name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - uses: actions/checkout@v2

      # Шаг 2: Установка JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      # Шаг 3: Даем права на выполнение gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Шаг 4: Запуск SUT
      - name: Start SUT
        run: java -jar ./artifacts/app-card-delivery.jar &
        # Здесь используется фоновый запуск (&), чтобы тесты могли выполняться параллельно

      # Шаг 5: Запуск автотестов
      - name: Run tests with Gradle
        run: ./gradlew test --info -Dselenide.headless=true
        # Параметр -Dselenide.headless=true включает headless-режим для браузера
